# Generated by Django 5.2.17 on 2026-08-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient Name')),
                ('pregnancies', models.IntegerField(verbose_name='Pregnancies')),
                ('glucose', models.FloatField(verbose_name='Glucose (mg/dL)')),
                ('blood_pressure', models.FloatField(verbose_name='Blood Pressure (mmHg)')),
                ('skin_thickness', models.FloatField(verbose_name='Skin Thickness (mm)')),
                ('insulin', models.FloatField(verbose_name='Insulin (µU/mL)')),
                ('bmi', models.FloatField(verbose_name='BMI (Weight in kg/(Height in m)²)')),
                ('diabetes_pedigree_function', models.FloatField(verbose_name='Diabetes Pedigree Function')),
                ('age', models.IntegerField(verbose_name='Age (years)')),
                ('prediction_class', models.BooleanField(verbose_name='Is Diabetic')),
                ('prediction_probability', models.FloatField(verbose_name='Diabetic Probability')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
