# Generated by Django 5.2.17 on 2026-08-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Assessment Date')),
                ('pregnancies', models.IntegerField(verbose_name='Pregnancies')),
                ('glucose', models.FloatField(verbose_name='Glucose')),
                ('blood_pressure', models.FloatField(verbose_name='Blood Pressure')),
                ('skin_thickness', models.FloatField(verbose_name='Skin Thickness')),
                ('insulin', models.FloatField(verbose_name='Insulin')),
                ('bmi', models.FloatField(verbose_name='BMI')),
                ('diabetes_pedigree_function', models.FloatField(verbose_name='Diabetes Pedigree Function')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('predicted_class', models.IntegerField(verbose_name='Predicted Class')),
                ('probability', models.FloatField(verbose_name='Risk Probability')),
                ('risk_level', models.CharField(max_length=15, verbose_name='Risk Level')),
            ],
            options={
                'verbose_name_plural': 'Prediction Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='PredictionRecord',
        ),
    ]
